apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-portfolio-backend
  namespace: stock-portfolio
  labels:
    app: stock-portfolio
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-portfolio
      component: backend
  template:
    metadata:
      labels:
        app: stock-portfolio
        component: backend
    spec:
      containers:
      - name: backend
        image: your-registry/stock-portfolio-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NOTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: stock-portfolio-secret
              key: NOTION_TOKEN
        - name: NOTION_DATABASE_ID
          valueFrom:
            secretKeyRef:
              name: stock-portfolio-secret
              key: NOTION_DATABASE_ID
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: stock-portfolio-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: stock-portfolio-config
              key: PORT
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: stock-portfolio-config
              key: CORS_ORIGIN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5 